name: Build and Deploy to Google Compute Engine
on: push
env:
  PROJECT_ID: ${{ secrets.GCE_PROJECT }}
  GCE_INSTANCE: pkt-builder
  GCE_INSTANCE_ZONE: us-central1-a

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
       ref: ci_cd_build # UPDATE TO MASTER WHEN DONE TESTNG
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Install Requirements and Dependencies
      run: pip install -r builds/build_requirements.txt

    - uses: google-github-actions/setup-gcloud@master
      with:
        version: '290.0.1'
        service_account_key: ${{ secrets.GCE_SA_KEY }}
        project_id: ${{ secrets.GCE_PROJECT }}
    - name: Configure Docker Authentication
      run: gcloud --quiet auth configure-docker

    - name: Build Docker Image
      run: docker build --tag "gcr.io/$PROJECT_ID/$GCE_INSTANCE-image:$GITHUB_SHA" -f builds/Dockerfile ./builds
    - name: Publish Docker Image to Google Container Registry
      run: docker push "gcr.io/$PROJECT_ID/$GCE_INSTANCE-image:$GITHUB_SHA"

    - name: Run Build Phases 1-2
      run: |-
        gcloud ai-platform jobs submit training "pkt_builder_phases_1_2_$GITHUB_SHA" \
          --scale-tier custom \
          --master-machine-type n1-highmem-8 \
          --region us-central1 \
          --master-image-uri "gcr.io/$PROJECT_ID/$GCE_INSTANCE-image:$GITHUB_SHA"
        python builds/job_monitoring.py --project "$PROJECT_ID"  --job "pkt_builder_phases_1_2_$GITHUB_SHA" --sleep 60
