name: Build and Deploy to Google Compute Engine
on: push
env:
  PROJECT_ID: ${{ secrets.GCE_PROJECT }}
  GCE_INSTANCE: pkt-builder
  GCE_INSTANCE_ZONE: us-central1-a

jobs:
#  pkt-build-phase-1-2:
#    name: KG Build Phases 1-2
#    runs-on: ubuntu-latest
#    steps:
#    - name: Checkout
#      uses: actions/checkout@v2
#      with:
#       ref: ci_cd_build # UPDATE TO MASTER WHEN DONE TESTNG
#    - name: Setup Python
#      uses: actions/setup-python@v2
#      with:
#        python-version: 3.6
#    - name: Install Requirements and Dependencies
#      run: pip install -r builds/build_requirements.txt pkt_kg
#    - uses: google-github-actions/setup-gcloud@master
#      with:
#        version: '290.0.1'
#        service_account_key: ${{ secrets.GCE_SA_KEY }}
#        project_id: ${{ secrets.GCE_PROJECT }}
#    - name: Configure Docker Authentication
#      run: gcloud --quiet auth configure-docker
#    - name: Build Docker Image
#      run: docker build --tag "gcr.io/$PROJECT_ID/pkt-builder-image:$GITHUB_SHA" -f builds/Dockerfile.phases12 ./builds
#    - name: Publish Docker Image to Google Container Registry
#      run: docker push "gcr.io/$PROJECT_ID/pkt-builder-image:$GITHUB_SHA"
#    - name: Submit Build Job to AI-Platform
#      run: |-
#        gcloud ai-platform jobs submit training "pkt_builder_phases_1_2_$GITHUB_SHA" \
#          --scale-tier custom \
#          --master-machine-type n1-highmem-16 \
#          --region us-central1 \
#          --master-image-uri "gcr.io/$PROJECT_ID/pkt-builder-image:$GITHUB_SHA"
#    - name: Monitor Build
#      run: |-
#        python builds/job_monitoring.py \
#          --instance_type reg --phase 1 --project "$PROJECT_ID" --job "pkt_builder_phases_1_2_$GITHUB_SHA" --sleep 60

  pkt-build-phase3-job1:
    needs: pkt-build-phase-1-2
    name: KG Build Phase 3 - Job 1 (Subclass + RelationsOnly + OWL)
    runs-on: ubuntu-latest
    env:
      ZONE: us-central1-a
      GCE_CPU: 1
      GCE_MEMORY: 250GB
      DOCKERFILE: Dockerfile.phase3
      IMAGE_TAG: "gcr.io/$PROJECT_ID/pkt-builder-phase3-job1-image:$GITHUB_SHA"
      JOB_NAME: kg-builder-phase3-job1
      KG_CONSTRUCT_APPROACH: 'subclass'
      RELATIONS: 'yes'
      OWL: 'yes'

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ci_cd_build # UPDATE TO MASTER WHEN DONE TESTNG
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Install Requirements and Dependencies
        run: pip install -r builds/build_requirements.txt pkt_kg
      - uses: google-github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          service_account_key: ${{ secrets.GCE_SA_KEY }}
          project_id: ${{ secrets.GCE_PROJECT }}
      - name: Configure Docker Authentication
        run: gcloud --quiet auth configure-docker
      - name: Build Docker Image
        run: |-
          docker build --tag "$IMAGE_TAG" -f builds/"$DOCKERFILE" ./builds \
            --build-arg "app_arg=$KG_CONSTRUCT_APPROACH" --build-arg "rel_arg=$RELATIONS" --build-arg "owl_arg=$OWL"
      - name: Publish Docker Image to Google Container Registry
        run: docker push "$IMAGE_TAG"
      - name: Create Virtual Machine Instance
        run: |-
          gcloud compute instances create-with-container "$JOB_NAME" \
            --container-image "$IMAGE_TAG" --container-restart-policy=never \
            --custom-cpu="$GCE_CPU" --custom-memory="$GCE_MEMORY" --custom-extensions --zone="$ZONE" --scopes=storage-rw
      - name: Monitor Build
        run: |-
          python builds/job_monitoring.py \
            --instance_type reg --phase 3 --project "" --job "" --sleep 60
      - name: Stop Virtual Machine Instance
        run: gcloud compute instances stop "$JOB_NAME" --zone="$ZONE"
      - name: Delete Virtual Machine Instance
        run: gcloud compute instances delete "$JOB_NAME" --zone="$ZONE"
