name: cloudrun-deploy
on: push
#  schedule:
#    - cron: '0 0 1 * *'  # runs midnight on the first day of each month
env:
  PROJECT_ID: ${{ secrets.GCE_PROJECT }}
  SERVICE: ${{ secrets.GCP_APPLICATION }}
  REGION: us-central1

jobs:
  setup-build-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
       ref: ci_cd_build # UPDATE TO MASTER WHEN DONE TESTNG

    - name: Setup Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ env.PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_CLOUD_RUN_CREDENTIALS }}

    - name: Authorize Docker Push
      run: gcloud auth configure-docker

    - name: Build and Push Container
      run: |-
        docker build -t gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:${{ github.sha }} -f builds/Dockerfile ./builds
        docker push gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:${{ github.sha }}

    - name: Deploy to Cloud Run
      run: |-
        gcloud run deploy ${{ env.SERVICE }} \
          --region ${{ env.REGION }} \
          --image gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:${{ github.sha }} \
          --platform "managed" \
          --port 8080 \
          --allow-unauthenticated \
          --cpu 4
          --memory 8GiB
