name: Build and Deploy to Google Compute Engine
on: push
env:
  PROJECT_ID: ${{ secrets.GCE_PROJECT }}
  GCS_SERVICE_ACCOUNT: ${{ secrets.GCE_SA_KEY }}

jobs:
#  pkt-build-phase-1-2:
#    name: KG Build Phases 1-2
#    runs-on: ubuntu-latest
#    env:
#      DOCKERFILE: builds/Dockerfile.phases12
#      GCE_MACHINE_TYPE: n1-highmem-16
#      GCE_REGION: us-central1
#    steps:
#    - name: Checkout
#      uses: actions/checkout@v2
#      with:
#       ref: ci_cd_build # UPDATE TO MASTER WHEN DONE TESTNG
#    - name: Setup Python
#      uses: actions/setup-python@v2
#      with:
#        python-version: 3.6
#    - name: Install Requirements and Dependencies
#      run: pip install -r builds/build_requirements.txt pkt_kg
#    - uses: google-github-actions/setup-gcloud@master
#      with:
#        version: '290.0.1'
#        service_account_key: ${{ secrets.GCE_SA_KEY }}
#        project_id: ${{ secrets.GCE_PROJECT }}
#    - name: Configure Docker Authentication
#      run: gcloud --quiet auth configure-docker
#    - name: Build Docker Image
#      run: docker build --tag "gcr.io/$PROJECT_ID/pkt_builder_phases_1_2_$GITHUB_SHA-image:$GITHUB_SHA" -f "$DOCKERFILE" ./builds
#    - name: Publish Docker Image to Google Container Registry
#      run: docker push "gcr.io/$PROJECT_ID/pkt_builder_phases_1_2_$GITHUB_SHA-image:$GITHUB_SHA"
#    - name: Submit Build Job to AI-Platform
#      run: |-
#        gcloud ai-platform jobs submit training "pkt_builder_phases_1_2_$GITHUB_SHA" \
#          --scale-tier custom --master-machine-type "$GCE_MACHINE_TYPE" --region "$GCE_REGION" \
#          --master-image-uri "gcr.io/$PROJECT_ID/pkt_builder_phases_1_2_$GITHUB_SHA-image:$GITHUB_SHA"
#    - name: Monitor Build
#      run: python builds/job_monitoring.py --gce_type reg --phase 1 --sleep 60 --gcs_dir '' --project '' --job ''

  pkt-build-phase3-job1:
#    needs: pkt-build-phase-1-2
    name: KG Build Phase 3 - Job 1 (Subclass + RelationsOnly + OWL)
    runs-on: ubuntu-latest
    env:
      GCE_ZONE: us-central1-a
      GCE_CPU: 1
      GCE_MEMORY: 250GB
      DOCKERFILE: builds/Dockerfile.phase3
      GCE_JOB_NAME: pkt-builder-phase3-job1
      GCS_LOCATION: 'subclass_builds/inverse_relations/owlnets'
      KG_CONSTRUCT_APPROACH: 'subclass'
      RELATIONS: 'yes'
      OWL: 'yes'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ci_cd_build # UPDATE TO MASTER WHEN DONE TESTNG
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Install Requirements and Dependencies
        run: pip install -r builds/build_requirements.txt pkt_kg
      - uses: google-github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          service_account_key: ${{ secrets.GCE_SA_KEY }}
          project_id: ${{ secrets.GCE_PROJECT }}
      - name: Configure Docker Authentication
        run: gcloud --quiet auth configure-docker
      - name: Build Docker Image
        run: |-
          docker build --tag "gcr.io/$PROJECT_ID/$GCE_JOB_NAME-image:$GITHUB_SHA" -f "$DOCKERFILE" ./builds \
            --build-arg "app_arg=$KG_CONSTRUCT_APPROACH" --build-arg "rel_arg=$RELATIONS" --build-arg "owl_arg=$OWL"
      - name: Publish Docker Image to Google Container Registry
        run: docker push "gcr.io/$PROJECT_ID/$GCE_JOB_NAME-image:$GITHUB_SHA"
      - name: Create Virtual Machine Instance
        run: |-
          gcloud compute instances create-with-container "$GCE_JOB_NAME" --zone="$GCE_ZONE" \
            --container-image "gcr.io/$PROJECT_ID/$GCE_JOB_NAME-image:$GITHUB_SHA" --container-restart-policy=never \
            --custom-cpu="$GCE_CPU" --custom-memory="$GCE_MEMORY" --custom-extensions --scopes=storage-rw
      - name: Monitor Build
        run: python builds/job_monitoring.py --gce_type reg --phase 3 --sleep 60 --gcs_dir "$GCS_LOCATION" --project '' --job ''
      - name: Stop Virtual Machine Instance
        run: gcloud compute instances stop "$GCE_JOB_NAME" --zone="$GCE_ZONE"
      - name: Delete Virtual Machine Instance
        run: gcloud compute instances delete "$GCE_JOB_NAME" --zone="$GCE_ZONE"
